## 서울시 공공자전거 대여소 정보 분석으로 판다스 입문하기

* 데이터 출처 : [서울시 공공자전거 대여소 정보> 데이터셋> 공공데이터 | 서울열린데이터광장](http://data.seoul.go.kr/dataList/OA-13252/F/1/datasetView.do)

<img src="https://pandas.pydata.org/docs/_static/pandas.svg" width="300">

## Pandas
* https://pandas.pydata.org/
* https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
* [10 minutes to pandas — pandasdocumentation](https://pandas.pydata.org/docs/user_guide/10min.html)
* [Pandas 10분 완성](https://dataitgirls2.github.io/10minutes2pandas/)

In [1]:
# pandas, numpy 불러오기
import numpy as np
import pandas as pd

## 데이터 불러오기

데이터 출처 : [서울시 공공자전거 대여소 정보> 데이터셋> 공공데이터 | 서울열린데이터광장](http://data.seoul.go.kr/dataList/OA-13252/F/1/datasetView.do)

In [2]:
# 공공자전거 대여소 정보(21.12월 기준).xlsx 파일을 불러옵니다. 
# sheet_name=2 에 해당 데이터가 있습니다.
# raw
raw = pd.read_excel('bycle.xlsx',sheet_name=2)
raw

,대여소\n번호,보관소(대여소)명,소재지(위치),Unnamed: 3,Unnamed: 4,Unnamed: 5,설치\n시기,설치형태,Unnamed: 8,운영\n방식
0,NaN,NaN,NaN,NaN,NaN,NaN,NaT,LCD,QR,NaN
1,NaN,NaN,자치구,상세주소,위도,경도,NaT,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaT,거치\n대수,거치\n대수,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20,20,QR
...,...,...,...,...,...,...,...,...,...,...
2761,3700.0,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08 00:00:00,NaN,8,QR
2762,3701.0,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12 00:00:00,NaN,8,QR
2763,4951.0,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29 00:00:00,NaN,5,QR
2764,4952.0,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18 00:00:00,NaN,5,QR
2765,4953.0,세양청마루 아파트 앞,강동구,강동구 천호대로 1162,37.533466,127.140503,2023-07-13 00:00:00,NaN,10,QR

## 데이터 전처리
### 컬럼명 변경하고 사용하지 않는 데이터 제거

In [3]:
# 컬럼 정보가 들어있는 데이터만 가져오기
raw.columns

Index(['대여소\n번호', '보관소(대여소)명', '소재지(위치)', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', '설치\n시기', '설치형태', 'Unnamed: 8', '운영\n방식'],
      dtype='object')

In [4]:
# 컬럼이름
col_names = ["대여소번호","대여소명", "자치구", "상세주소", "위도", "경도", "설치시기", "LCD", "QR", "운영방식"]
col_names

['대여소번호', '대여소명', '자치구', '상세주소', '위도', '경도', '설치시기', 'LCD', 'QR', '운영방식']

In [9]:
# 컬럼명 변경하고 4번 인덱스 행부터 사용하기
# df
raw.columns = col_names
df = raw[4:].copy()
df

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식
4,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20,20,QR
5,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.97406,2015-10-07 12:04:22,12,12,QR
6,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.57177,126.974663,2015-10-07 00:00:00,8,8,QR
7,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00,16,16,QR
8,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.57,126.9711,2015-10-07 12:09:09,11,11,QR
...,...,...,...,...,...,...,...,...,...,...
2761,3700.0,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08 00:00:00,NaN,8,QR
2762,3701.0,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12 00:00:00,NaN,8,QR
2763,4951.0,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29 00:00:00,NaN,5,QR
2764,4952.0,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18 00:00:00,NaN,5,QR
2765,4953.0,세양청마루 아파트 앞,강동구,강동구 천호대로 1162,37.533466,127.140503,2023-07-13 00:00:00,NaN,10,QR

### 인덱스 초기화

In [10]:
# reset_index 로 초기화를 합니다. 기존 인덱스는 제거합니다.
# df
df = df.reset_index(drop=True)
df

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20,20,QR
1,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.97406,2015-10-07 12:04:22,12,12,QR
2,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.57177,126.974663,2015-10-07 00:00:00,8,8,QR
3,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00,16,16,QR
4,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.57,126.9711,2015-10-07 12:09:09,11,11,QR
...,...,...,...,...,...,...,...,...,...,...
2757,3700.0,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08 00:00:00,NaN,8,QR
2758,3701.0,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12 00:00:00,NaN,8,QR
2759,4951.0,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29 00:00:00,NaN,5,QR
2760,4952.0,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18 00:00:00,NaN,5,QR
2761,4953.0,세양청마루 아파트 앞,강동구,강동구 천호대로 1162,37.533466,127.140503,2023-07-13 00:00:00,NaN,10,QR

## 데이터 요약

In [68]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2762 entries, 0 to 2761
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대여소번호   2762 non-null   float64
 1   대여소명    2762 non-null   object
 2   자치구     2762 non-null   object
 3   상세주소    2762 non-null   object
 4   위도      2762 non-null   object
 5   경도      2762 non-null   object
 6   설치시기    2762 non-null   datetime64[ns]
 7   LCD     1454 non-null   object
 8   QR      1653 non-null   object
 9   운영방식    2762 non-null   object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 215.9+ KB

## 데이터 타입 변경하기

In [12]:
df['위도'].describe()

count     2762.000000
unique    2667.000000
top         37.561447
freq         2.000000
Name: 위도, dtype: float64

In [70]:
# nan == not a number의 약자로 결측치를 의미한다.
# nan값이 존재하면 시리즈 타입은 float64로 변경된다.
type(np.nan)

float

In [14]:
pd.Series([1,2,3,4,np.nan])

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [17]:
# 위도, 경도, LCD, QR을 수치 형태로 변경합니다.
# df["LCD"]
# df["QR"]
df['위도'] = df['위도'].astype(float)  #df['위도'] = df['위도'].astype(np.float32)
df['경도'] = df['경도'].astype(float)
df['LCD'] = df['LCD'].astype(float)
df['QR'] = df['QR'].astype(float)

In [18]:
df['위도'].describe()
df['LCD'].describe()
# df['자치구'].describe()

count    1454.000000
mean       12.620358
std         4.962103
min         5.000000
25%        10.000000
50%        10.000000
75%        15.000000
max        46.000000
Name: LCD, dtype: float64

## Attributes를 통한 데이터의 개별 정보 보기
* https://pandas.pydata.org/docs/reference/frame.html

In [84]:
# shape
df.shape

(2762, 10)

In [85]:
# dtypes
df.dtypes

대여소번호           float64
대여소명             object
자치구              object
상세주소             object
위도              float64
경도              float64
설치시기     datetime64[ns]
LCD             float64
QR              float64
운영방식             object
dtype: object

In [86]:
# index
df.index

RangeIndex(start=0, stop=2762, step=1)

In [87]:
# columns
df.columns

Index(['대여소번호', '대여소명', '자치구', '상세주소', '위도', '경도', '설치시기', 'LCD', 'QR',
       '운영방식'],
      dtype='object')

In [88]:
# values
df.values

array([[301.0, ' 경복궁역 7번출구 앞', '종로구', ..., 20.0, 20.0, 'QR'],
       [302.0, ' 경복궁역 4번출구 뒤', '종로구', ..., 12.0, 12.0, 'QR'],
       [303.0, ' 광화문역 1번출구 앞', '종로구', ..., 8.0, 8.0, 'QR'],
       ...,
       [4951.0, ' 강동농협 버스정류소 앞(광채빌라)', '강동구', ..., nan, 5.0, 'QR'],
       [4952.0, '천호시장 버스정류소 옆', '강동구', ..., nan, 5.0, 'QR'],
       [4953.0, '세양청마루 아파트 앞', '강동구', ..., nan, 10.0, 'QR']], dtype=object)

## 중복확인

In [22]:
# duplicated 확인
df[df.duplicated()]

Empty DataFrame
Columns: [대여소번호, 대여소명, 자치구, 상세주소, 위도, 경도, 설치시기, LCD, QR, 운영방식]
Index: []

## 결측치 확인
### 결측치 합계

In [94]:
True == 1

True

In [95]:
True + True + False + True

3

In [24]:
# 결측치 합계
df.isnull().sum()

대여소번호       0
대여소명        0
자치구         0
상세주소        0
위도          0
경도          0
설치시기        0
LCD      1308
QR       1109
운영방식        0
dtype: int64

### 결측치 비율

In [98]:
# 결측치 비율
df.isnull().mean() * 100

대여소번호     0.000000
대여소명      0.000000
자치구       0.000000
상세주소      0.000000
위도        0.000000
경도        0.000000
설치시기      0.000000
LCD      47.356988
QR       40.152064
운영방식      0.000000
dtype: float64

### LCD, QR 둘 다 운영중인 대여소 찾기

In [25]:
# LCD, QR 둘다 notnull 인 곳 == 운영중인 곳
df[df['LCD'].notnull() & df['QR'].notnull()]

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20.0,20.0,QR
1,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07 12:04:22,12.0,12.0,QR
2,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07 00:00:00,8.0,8.0,QR
3,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00,16.0,16.0,QR
4,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07 12:09:09,11.0,11.0,QR
...,...,...,...,...,...,...,...,...,...,...
2506,2608.0,송파구청,송파구,송파구 올림픽로 326,37.515053,127.106270,2018-11-12 00:00:00,15.0,10.0,QR
2516,2619.0,석촌고분역 4번출구,송파구,송파구 삼전동 90,37.502338,127.096443,2018-11-14 00:00:00,9.0,9.0,QR
2657,1018.0,둔촌 주공 GS 맞은편,강동구,서울특별시 강동구 양재대로 1330,37.524590,127.135422,2017-06-22 10:08:54,20.0,15.0,QR
2672,1033.0,고덕동 아남아파트,강동구,서울특별시 고덕동 673,37.557934,127.144768,2017-11-01 16:00:00,10.0,17.0,QR
2687,1053.0,동명근린공원 진입로 (아리수로),강동구,고덕동 230,37.562546,127.164482,2018-09-03 00:00:00,8.0,3.0,LCD

## 파생변수 만들기

In [101]:
np.nan +  1

nan

In [27]:
pd.Series([np.nan]).fillna(0) + 1

0    1.0
dtype: float64

In [28]:
# LCD, QR을 더해서 자전거수 파생변수 만들기
# df["자전거수"]
df['자전거수'] = df['LCD'].fillna(0) + df['QR'].fillna(0)
df['자전거수'].isnull().sum()
df['자전거수'] = df['자전거수'].astype(int)
df.dtypes

대여소번호           float64
대여소명             object
자치구              object
상세주소             object
위도              float64
경도              float64
설치시기     datetime64[ns]
LCD             float64
QR              float64
운영방식             object
자전거수              int32
dtype: object

In [29]:
df.head()

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20.0,20.0,QR,40
1,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07 12:04:22,12.0,12.0,QR,24
2,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07 00:00:00,8.0,8.0,QR,16
3,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00,16.0,16.0,QR,32
4,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07 12:09:09,11.0,11.0,QR,22

In [30]:
# 연도 파생변수 만들기
# df["연도"]
df['연도']=df['설치시기'].dt.year
df.head(1)

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20.0,20.0,QR,40,2015

In [31]:
# 월(month), 일(day), 요일(dayofweek) 만들기
# df["월"]
# df["일"]
# df["요일"]
df['월'] = df['설치시기'].dt.month
df['일'] = df['설치시기'].dt.day
df['요일'] = df['설치시기'].dt.dayofweek
df.head(1)

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20.0,20.0,QR,40,2015,10,7,2

## 기초 기술통계

In [32]:
# describe
df.describe()

,대여소번호,위도,경도,설치시기,LCD,QR,자전거수,연도,월,일,요일
count,2762.000000,2762.000000,2762.000000,2762,1454.000000,1653.000000,2762.000000,2762.000000,2762.000000,2762.000000,2762.000000
mean,2351.479363,37.547397,126.991328,2019-03-22 19:28:10.305573632,12.620358,12.035088,13.846488,2018.711803,6.653150,15.249457,2.007603
min,102.000000,37.430977,126.798599,2015-01-07 00:00:00,5.000000,2.000000,2.000000,2015.000000,1.000000,1.000000,0.000000
25%,1009.250000,37.505236,126.914299,2017-06-20 10:01:52.249999872,10.000000,10.000000,10.000000,2017.000000,4.000000,7.000000,1.000000
50%,2070.500000,37.545483,127.003372,2018-11-14 00:00:00,10.000000,10.000000,10.000000,2018.000000,6.000000,14.500000,2.000000
75%,3779.750000,37.577336,127.063763,2020-12-03 00:00:00,15.000000,15.000000,15.000000,2020.000000,10.000000,24.000000,3.000000
max,6172.000000,37.691013,127.180756,2023-12-12 00:00:00,46.000000,62.000000,92.000000,2023.000000,12.000000,31.000000,6.000000
std,1569.395956,0.052343,0.092762,NaN,4.962103,6.079476,8.445683,2.135283,3.349264,9.572558,1.431376

In [121]:
# describe
df.describe(include='O')
df.describe(include='all')

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
count,2762.000000,2762,2762,2762,2762.000000,2762.000000,2762,1454.000000,1653.000000,2762,2762.000000,2762.000000,2762.000000,2762.000000,2762.000000
unique,NaN,2761,25,2682,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN
top,NaN,한양수자인아파트 앞,송파구,국회의사당 경내,NaN,NaN,NaN,NaN,NaN,QR,NaN,NaN,NaN,NaN,NaN
freq,NaN,2,217,7,NaN,NaN,NaN,NaN,NaN,1648,NaN,NaN,NaN,NaN,NaN
mean,2351.479363,NaN,NaN,NaN,37.547397,126.991328,2019-03-22 19:28:10.305573632,12.620358,12.035088,NaN,13.846488,2018.711803,6.653150,15.249457,2.007603
min,102.000000,NaN,NaN,NaN,37.430977,126.798599,2015-01-07 00:00:00,5.000000,2.000000,NaN,2.000000,2015.000000,1.000000,1.000000,0.000000
25%,1009.250000,NaN,NaN,NaN,37.505236,126.914299,2017-06-20 10:01:52.249999872,10.000000,10.000000,NaN,10.000000,2017.000000,4.000000,7.000000,1.000000
50%,2070.500000,NaN,NaN,NaN,37.545483,127.003372,2018-11-14 00:00:00,10.000000,10.000000,NaN,10.000000,2018.000000,6.000000,14.500000,2.000000
75%,3779.750000,NaN,NaN,NaN,37.577336,127.063763,2020-12-03 00:00:00,15.000000,15.000000,NaN,15.000000,2020.000000,10.000000,24.000000,3.000000
max,6172.000000,NaN,NaN,NaN,37.691013,127.180756,2023-12-12 00:00:00,46.000000,62.000000,NaN,92.000000,2023.000000,12.000000,31.000000,6.000000
std,1569.395956,NaN,NaN,NaN,0.052343,0.092762,NaN,4.962103,6.079476,NaN,8.445683,2.135283,3.349264,9.572558,1.431376

In [36]:
# 대여소명 양쪽 공백제거
df['대여소명'] = df['대여소명'].str.strip()

In [47]:
# 레코드 필터링
tmp = df[df['대여소명'] == '효자동 삼거리']
tmp

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
49,450.0,효자동 삼거리,종로구,서울특별시 종로구 효자로13길 45 종로구 궁정동 98-2,37.583603,126.972549,2017-09-07 16:05:37,20.0,51.0,QR,71,2017,9,7,3

## 정렬하기

### 자전거 수가 많은 대여소

In [50]:
# sort_values 로 "자전거수"가 많은 대여소 찾기
df.sort_values(by='자전거수',ascending=False).head(10)

df.sort_values(by=['LCD','QR'],ascending=[False,True]).head(10)

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
1800,207.0,여의나루역 1번출구 앞,영등포구,서울특별시 영등포구 여의동로 지하343,37.527157,126.931900,2015-09-17 15:33:18,46.0,46.0,QR,92,2015,9,17,3
421,574.0,아차산역4번출구,광진구,서울특별시 광진구 능동로 216 아차산역4번출구,37.551849,127.088982,2016-07-06 12:00:00,45.0,45.0,QR,90,2016,7,6,2
1240,420.0,서울시 공공자전거 상암센터,마포구,서울특별시 마포구 월드컵북로47길 10,37.566246,126.896179,2015-10-07 11:39:12,40.0,37.0,QR,77,2015,10,7,2
1219,186.0,월드컵공원,마포구,서울특별시 마포구 하늘공원로 108-1,37.563965,126.898209,2016-07-06 12:00:00,40.0,40.0,QR,80,2016,7,6,2
214,829.0,한강대교 북단 교차로,용산구,서울특별시 용산구 한강대로 23 베르가모앞,37.522930,126.961693,2017-11-28 11:57:57,40.0,NaN,LCD,40,2017,11,28,1
1196,124.0,서강대 정문 건너편,마포구,서울특별시 마포구 서강로16길 72,37.551140,126.936989,2015-09-07 10:33:08,35.0,35.0,QR,70,2015,9,7,0
1799,206.0,KBS 앞,영등포구,서울특별시 영등포구 여의공원로 13,37.524666,126.918022,2015-09-17 15:09:17,35.0,35.0,QR,70,2015,9,17,3
1486,1198.0,LG 사이언스파크,강서구,강서구 마곡동 727-925,37.562550,126.827438,2018-11-20 00:00:00,31.0,NaN,LCD,31,2018,11,20,1
203,815.0,LIG강촌아파트 103동앞,용산구,서울특별시 용산구 이촌동301-5 LIG강촌아파트 103동앞,37.518509,126.978798,2016-06-29 12:00:00,30.0,30.0,QR,60,2016,6,29,2
1220,199.0,서울 월드컵 경기장,마포구,서울특별시 마포구 성산동 515,37.566845,126.896446,2016-09-02 11:00:00,30.0,30.0,QR,60,2016,9,2,4

In [147]:
# nlargest 로 "자전거수"가 많은 대여소 찾기
df.nlargest(10,'자전거수')

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
1800,207.0,여의나루역 1번출구 앞,영등포구,서울특별시 영등포구 여의동로 지하343,37.527157,126.931900,2015-09-17 15:33:18.000,46.0,46.0,QR,92,2015,9,17,3
421,574.0,아차산역4번출구,광진구,서울특별시 광진구 능동로 216 아차산역4번출구,37.551849,127.088982,2016-07-06 12:00:00.000,45.0,45.0,QR,90,2016,7,6,2
1219,186.0,월드컵공원,마포구,서울특별시 마포구 하늘공원로 108-1,37.563965,126.898209,2016-07-06 12:00:00.000,40.0,40.0,QR,80,2016,7,6,2
1240,420.0,서울시 공공자전거 상암센터,마포구,서울특별시 마포구 월드컵북로47길 10,37.566246,126.896179,2015-10-07 11:39:12.000,40.0,37.0,QR,77,2015,10,7,2
49,450.0,효자동 삼거리,종로구,서울특별시 종로구 효자로13길 45 종로구 궁정동 98-2,37.583603,126.972549,2017-09-07 16:05:37.000,20.0,51.0,QR,71,2017,9,7,3
1196,124.0,서강대 정문 건너편,마포구,서울특별시 마포구 서강로16길 72,37.551140,126.936989,2015-09-07 10:33:08.000,35.0,35.0,QR,70,2015,9,7,0
1799,206.0,KBS 앞,영등포구,서울특별시 영등포구 여의공원로 13,37.524666,126.918022,2015-09-17 15:09:17.000,35.0,35.0,QR,70,2015,9,17,3
583,1452.0,겸재교 진입부,중랑구,서울특별시 중랑구 겸재로 68 겸재교진입부,37.585655,127.075050,2017-11-29 12:04:30.995,20.0,45.0,LCD,65,2017,11,29,2
1503,2717.0,LG유플러스 마곡사옥,강서구,강서구 마곡중앙8로 71,37.561337,126.833900,2020-03-15 00:00:00.000,NaN,62.0,QR,62,2020,3,15,6
203,815.0,LIG강촌아파트 103동앞,용산구,서울특별시 용산구 이촌동301-5 LIG강촌아파트 103동앞,37.518509,126.978798,2016-06-29 12:00:00.000,30.0,30.0,QR,60,2016,6,29,2

In [148]:
df.nsmallest(10,'자전거수')

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
376,4394.0,서울시립24시간게스트하우스,성동구,성동구 송정동 73-1113,37.554333,127.058228,2023-12-08,NaN,2.0,QR,2,2023,12,8,4
1602,5100.0,강서도로사업소,강서구,마곡동 60-8,37.573318,126.830071,2023-09-04,NaN,2.0,QR,2,2023,9,4,0
457,3882.0,자양2동 주민센터,광진구,서울특별시 광진구 자양로3가길 28,37.528793,127.084633,2021-07-23,NaN,3.0,QR,3,2021,7,23,4
360,4363.0,신금호역 2번출구 앞,성동구,서울특별시 성동구 신금호역 2번출구,37.555073,127.019890,2021-06-25,NaN,4.0,QR,4,2021,6,25,4
367,4383.0,푸조비즈타워 앞,성동구,서울특별시 성동구 성동구 광나루로 310,37.548080,127.064613,2022-02-10,NaN,4.0,QR,4,2022,2,10,3
844,4080.0,창동주공19단지앞,도봉구,서울특별시 도봉구 도봉시 노해로 70길 19 1905동 앞 ( 도봉경찰서 건너편) ...,37.652508,127.052277,2021-10-27,NaN,4.0,QR,4,2021,10,27,2
974,4044.0,공릉산 백세문 입구,노원구,서울특별시 노원구 노원로 62 공릉해링턴플레이스,37.628120,127.085487,2021-10-07,NaN,4.0,QR,4,2021,10,7,3
976,5301.0,상계주공1단지 버스정류장 옆(대원빌딩 앞),노원구,서울특별시 노원구 동일로 1331-2 구두수선대,37.648060,127.062393,2021-12-15,NaN,4.0,QR,4,2021,12,15,2
2024,4180.0,흑석동주민센터 입구,동작구,동작구 흑석동 25-21,37.506828,126.966736,2022-07-18,NaN,4.0,QR,4,2022,7,18,0
2386,3629.0,청담사거리(신한오피스텔빌딩 앞),강남구,도산대로 510,37.524162,127.048950,2021-02-23,NaN,4.0,QR,4,2021,2,23,1

## DataFrame

<img src="https://pandas.pydata.org/docs/_images/01_table_dataframe.svg">

In [51]:
# df 의 type 확인
type(df)

pandas.core.frame.DataFrame

## Series

<img src="https://pandas.pydata.org/docs/_images/01_table_series.svg">

In [52]:
# series 의 type 확인
type(df['대여소명'])

pandas.core.series.Series

In [60]:
# 컬럼 인덱싱
df['대여소명']

0              경복궁역 7번출구 앞
1              경복궁역 4번출구 뒤
2              광화문역 1번출구 앞
3                   종로구청 옆
4                서울역사박물관 앞
               ...
2757       강변그대가리버뷰 입구 맞은편
2758                 방아삼거리
2759    강동농협 버스정류소 앞(광채빌라)
2760          천호시장 버스정류소 옆
2761           세양청마루 아파트 앞
Name: 대여소명, Length: 2762, dtype: object

In [56]:
# 2개 이상의 컬럼 인덱싱
df[['대여소명','상세주소']]

                    대여소명                             상세주소
0            경복궁역 7번출구 앞  서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞
1            경복궁역 4번출구 뒤  서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤
2            광화문역 1번출구 앞       서울특별시 종로구 세종대로 지하189 세종로공원
3                 종로구청 옆               서울특별시 종로구 세종로 84-1
4              서울역사박물관 앞      서울특별시 종로구 새문안로 55 서울역사박물관 앞
...                  ...                              ...
2757     강변그대가리버뷰 입구 맞은편                    강동구 천호동 250-7
2758               방아삼거리                    강동구 둔촌동 118-2
2759  강동농협 버스정류소 앞(광채빌라)                   강동구 암사동 488-21
2760        천호시장 버스정류소 옆                  강동구 천호동 397-465
2761         세양청마루 아파트 앞                    강동구 천호대로 1162

[2762 rows x 2 columns]

## loc

In [63]:
# loc를 통한 행 인덱싱
df.loc[0]

대여소번호                              301.0
대여소명                         경복궁역 7번출구 앞
자치구                                  종로구
상세주소     서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞
위도                             37.575794
경도                            126.971451
설치시기                 2015-10-07 12:03:46
LCD                                 20.0
QR                                  20.0
운영방식                                  QR
자전거수                                  40
연도                                  2015
월                                     10
일                                      7
요일                                     2
Name: 0, dtype: object

In [64]:
# 여러 행 인덱싱
df.loc[[0,1,2]]

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20.0,20.0,QR,40,2015,10,7,2
1,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07 12:04:22,12.0,12.0,QR,24,2015,10,7,2
2,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07 00:00:00,8.0,8.0,QR,16,2015,10,7,2

In [65]:
# 행, 열 인덱싱
df.loc[0,'대여소명']

'경복궁역 7번출구 앞'

In [72]:
# 행, 열 슬라이싱
print(df.loc[:3,['상세주소','대여소명']])
display(df.loc[:3,['상세주소','대여소명']])

df.loc[:3,'상세주소':'경도']

                              상세주소         대여소명
0  서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞  경복궁역 7번출구 앞
1  서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤  경복궁역 4번출구 뒤
2       서울특별시 종로구 세종대로 지하189 세종로공원  광화문역 1번출구 앞
3               서울특별시 종로구 세종로 84-1       종로구청 옆

                              상세주소         대여소명
0  서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞  경복궁역 7번출구 앞
1  서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤  경복궁역 4번출구 뒤
2       서울특별시 종로구 세종대로 지하189 세종로공원  광화문역 1번출구 앞
3               서울특별시 종로구 세종로 84-1       종로구청 옆

                              상세주소         위도          경도
0  서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞  37.575794  126.971451
1  서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤  37.575947  126.974060
2       서울특별시 종로구 세종대로 지하189 세종로공원  37.571770  126.974663
3               서울특별시 종로구 세종로 84-1  37.572559  126.978333

### iloc

In [78]:
# iloc 를 통한 인덱싱
df.iloc[0,1]

'경복궁역 7번출구 앞'

In [79]:
# iloc 를 통한 슬라이싱
df.iloc[:3,:3]

   대여소번호         대여소명  자치구
0  301.0  경복궁역 7번출구 앞  종로구
1  302.0  경복궁역 4번출구 뒤  종로구
2  303.0  광화문역 1번출구 앞  종로구

In [80]:
df.iloc[:3, 0]

0    301.0
1    302.0
2    303.0
Name: 대여소번호, dtype: float64

## 조건 검색
<img src="https://pandas.pydata.org/docs/_images/03_subset_columns_rows.svg">

In [92]:
# Boolean Indexing
# 마포구 대여소 찾기
df[df['자치구'] == '마포구']
df[(df['자치구'] == '마포구') | (df['자치구'] == '종로구')]
df[~((df['자치구'] == '마포구') | (df['자치구'] == '종로구'))]
df[(df['LCD'] >= 5) & (df['QR'] >= 5)]

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20.0,20.0,QR,40,2015,10,7,2
1,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07 12:04:22,12.0,12.0,QR,24,2015,10,7,2
2,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07 00:00:00,8.0,8.0,QR,16,2015,10,7,2
3,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00,16.0,16.0,QR,32,2015,1,7,2
4,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07 12:09:09,11.0,11.0,QR,22,2015,10,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2483,1278.0,송파구청 교차로,송파구,서울특별시 송파구 올림픽로 336,37.515797,127.106819,2018-02-26 11:50:05,10.0,16.0,QR,26,2018,2,26,0
2506,2608.0,송파구청,송파구,송파구 올림픽로 326,37.515053,127.106270,2018-11-12 00:00:00,15.0,10.0,QR,25,2018,11,12,0
2516,2619.0,석촌고분역 4번출구,송파구,송파구 삼전동 90,37.502338,127.096443,2018-11-14 00:00:00,9.0,9.0,QR,18,2018,11,14,2
2657,1018.0,둔촌 주공 GS 맞은편,강동구,서울특별시 강동구 양재대로 1330,37.524590,127.135422,2017-06-22 10:08:54,20.0,15.0,QR,35,2017,6,22,3
2672,1033.0,고덕동 아남아파트,강동구,서울특별시 고덕동 673,37.557934,127.144768,2017-11-01 16:00:00,10.0,17.0,QR,27,2017,11,1,2

In [97]:
# isin 으로 "마포구", "종로구" 대여소 찾기
df[df['자치구'].isin(['마포구','종로구'])]
df[~df['자치구'].isin(['마포구','종로구'])]

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
102,300.0,정동사거리,중구,서울특별시 중구 정동길 2-1 정동사거리,37.568050,126.969231,2015-10-07 00:00:00,7.0,6.0,QR,13,2015,10,7,2
103,310.0,청계광장 옆,중구,서울특별시 중구 세종대로 136 청계광장 옆,37.568878,126.977470,2015-10-07 12:11:15,13.0,8.0,QR,21,2015,10,7,2
104,318.0,광교사거리 남측,중구,서울특별시 중구 남대문로 125 DGB금융센터,37.568634,126.982315,2015-10-07 12:16:35,10.0,10.0,QR,20,2015,10,7,2
105,320.0,을지로입구역 4번출구 앞,중구,서울특별시 중구 을지로 55 명동금융센터 앞,37.566223,126.983589,2015-10-07 12:18:35,20.0,17.0,QR,37,2015,10,7,2
106,321.0,KEB 하나금융그룹 명동사옥 옆,중구,서울특별시 중구 을지로 66 한국외환은행 본점 앞,37.565464,126.984138,2015-10-07 12:19:23,15.0,15.0,QR,30,2015,10,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2757,3700.0,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08 00:00:00,NaN,8.0,QR,8,2022,7,8,4
2758,3701.0,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12 00:00:00,NaN,8.0,QR,8,2022,10,12,2
2759,4951.0,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29 00:00:00,NaN,5.0,QR,5,2022,9,29,3
2760,4952.0,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18 00:00:00,NaN,5.0,QR,5,2023,1,18,2
2761,4953.0,세양청마루 아파트 앞,강동구,강동구 천호대로 1162,37.533466,127.140503,2023-07-13 00:00:00,NaN,10.0,QR,10,2023,7,13,3

In [99]:
# 여러 조건 비교하기
# 마포구의 LCD 운영 대여소 찾기
df[(df['자치구'] == '마포구') & (df['운영방식'] == 'LCD')]

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
1201,142.0,아현역 4번출구 앞,마포구,서울특별시 마포구 아현동 329-15,37.557201,126.955666,2016-06-29 12:00:00,11.0,NaN,LCD,11,2016,6,29,2
1202,143.0,공덕역 2번출구,마포구,서울특별시 마포구 공덕동 257-88,37.544579,126.950218,2016-06-29 12:00:00,9.0,NaN,LCD,9,2016,6,29,2
1203,144.0,공덕역 8번출구,마포구,서울특별시 마포구 공덕동 438-5,37.543579,126.951324,2016-06-29 12:00:00,10.0,NaN,LCD,10,2016,6,29,2
1204,145.0,공덕역 5번출구,마포구,서울특별시 마포구 공덕동 237-9,37.544250,126.951637,2016-06-29 12:00:00,9.0,NaN,LCD,9,2016,6,29,2
1205,146.0,마포역 2번출구 뒤,마포구,서울특별시 마포구 도화동 555-2,37.539936,126.945824,2016-06-29 12:00:00,12.0,NaN,LCD,12,2016,6,29,2
1209,153.0,성산2교 사거리,마포구,서울특별시 마포구 성산동 54-17,37.564697,126.912613,2016-06-29 12:00:00,10.0,NaN,LCD,10,2016,6,29,2
1210,154.0,마포구청역,마포구,서울특별시 마포구 망원동 477-23,37.560909,126.905495,2016-06-29 12:00:00,13.0,NaN,LCD,13,2016,6,29,2
1213,157.0,애오개역 4번출구 앞,마포구,서울특별시 마포구 아현동 607-1,37.553001,126.956688,2016-06-29 12:00:00,12.0,NaN,LCD,12,2016,6,29,2
1214,181.0,망원초록길 입구,마포구,서울특별시 마포구 마포나루길 467,37.551342,126.902672,2016-07-06 12:00:00,15.0,NaN,LCD,15,2016,7,6,2
1216,183.0,하늘채코오롱아파트 건너편,마포구,서울특별시 마포구 연남로 30,37.565166,126.919395,2016-07-06 12:00:00,15.0,NaN,LCD,15,2016,7,6,2
1243,424.0,롯데하이마트 (상암월드컵점),마포구,서울특별시 상암동 1715-29,37.573620,126.898048,2017-11-01 16:00:00,15.0,NaN,LCD,15,2017,11,1,2
1244,425.0,DMC첨단산업센터,마포구,서울특별시 마포구 성암로330,37.584503,126.885597,2017-11-01 16:00:00,10.0,NaN,LCD,10,2017,11,1,2
1245,426.0,서울신용보증재단,마포구,서울특별시 마포구 마포대로 163,37.549061,126.954178,2018-07-04 00:00:00,10.0,NaN,LCD,10,2018,7,4,2
1246,427.0,성산시영아파트,마포구,서울특별시 마포구 월드컵북로 260,37.569584,126.903816,2018-02-26 11:34:06,10.0,NaN,LCD,10,2018,2,26,0
1247,432.0,마포중앙도서관,마포구,마포구 성산로 128,37.563339,126.908203,2018-10-12 00:00:00,10.0,NaN,LCD,10,2018,10,12,4
1248,436.0,이대역 5번출구,마포구,마포구 대흥동 2-1,37.556591,126.946190,2018-11-21 00:00:00,10.0,NaN,LCD,10,2018,11,21,2
1249,437.0,대흥역1번출구,마포구,마포구 대흥동 105-4,37.548470,126.940926,2018-12-04 00:00:00,12.0,NaN,LCD,12,2018,12,4,1
1250,438.0,성산2-1 공영주차장,마포구,마포구 성산동 199-46,37.564720,126.906769,2018-11-22 00:00:00,15.0,NaN,LCD,15,2018,11,22,3
1251,440.0,하늘공원 입구,마포구,마포구 하늘공원로 108-2,37.570122,126.881348,2019-08-02 00:00:00,15.0,NaN,LCD,15,2019,8,2,4

In [111]:
# 여러 조건 비교하기
# 상세주소에 월드컵로가 들어가는 LCD운영 대여소 찾기

df[(df['상세주소'].str.contains('월드컵')) & (df['운영방식'] == 'LCD')]

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
1246,427.0,성산시영아파트,마포구,서울특별시 마포구 월드컵북로 260,37.569584,126.903816,2018-02-26 11:34:06,10.0,NaN,LCD,10,2018,2,26,0

In [115]:
# 자전거수가 특정 수 이상 있는 대여소 찾기
df[df['자전거수'] > 30]
df[df['자전거수'] > 30].loc[:3,['자치구','상세주소','자전거수']]

   자치구                             상세주소  자전거수
0  종로구  서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞    40
3  종로구               서울특별시 종로구 세종로 84-1    32

## 전처리 내용 파일저장하기

<img src="https://pandas.pydata.org/docs/_images/02_io_readwrite.svg">

In [116]:
df

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20.0,20.0,QR,40,2015,10,7,2
1,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07 12:04:22,12.0,12.0,QR,24,2015,10,7,2
2,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07 00:00:00,8.0,8.0,QR,16,2015,10,7,2
3,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00,16.0,16.0,QR,32,2015,1,7,2
4,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07 12:09:09,11.0,11.0,QR,22,2015,10,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2757,3700.0,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08 00:00:00,NaN,8.0,QR,8,2022,7,8,4
2758,3701.0,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12 00:00:00,NaN,8.0,QR,8,2022,10,12,2
2759,4951.0,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29 00:00:00,NaN,5.0,QR,5,2022,9,29,3
2760,4952.0,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18 00:00:00,NaN,5.0,QR,5,2023,1,18,2
2761,4953.0,세양청마루 아파트 앞,강동구,강동구 천호대로 1162,37.533466,127.140503,2023-07-13 00:00:00,NaN,10.0,QR,10,2023,7,13,3

In [121]:
# 파일명 지정하기
file_name = "bike_station.csv"
file_name

'bike_station.csv'

In [123]:
# to_csv 로 저장하고 index=False 로 인덱스는 제외하고 저장하기
df.to_csv(file_name,index=False)

In [124]:
# read_csv 로 저장한 파일 읽어와서 확인하기
df = pd.read_csv(file_name)
df

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46.000,20.0,20.0,QR,40,2015,10,7,2
1,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07 12:04:22.000,12.0,12.0,QR,24,2015,10,7,2
2,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07 00:00:00.000,8.0,8.0,QR,16,2015,10,7,2
3,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00.000,16.0,16.0,QR,32,2015,1,7,2
4,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07 12:09:09.000,11.0,11.0,QR,22,2015,10,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2757,3700.0,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08 00:00:00.000,NaN,8.0,QR,8,2022,7,8,4
2758,3701.0,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12 00:00:00.000,NaN,8.0,QR,8,2022,10,12,2
2759,4951.0,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29 00:00:00.000,NaN,5.0,QR,5,2022,9,29,3
2760,4952.0,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18 00:00:00.000,NaN,5.0,QR,5,2023,1,18,2
2761,4953.0,세양청마루 아파트 앞,강동구,강동구 천호대로 1162,37.533466,127.140503,2023-07-13 00:00:00.000,NaN,10.0,QR,10,2023,7,13,3

* https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [125]:
# to_xlsx 로 저장하고 index=False 로 인덱스는 제외하고 저장하기
file_name = "bike_station.xlsx"
df.to_excel(file_name,index=False)

In [126]:
df2 = pd.read_excel(file_name)
df2

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
0,301,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46.000,20.0,20.0,QR,40,2015,10,7,2
1,302,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07 12:04:22.000,12.0,12.0,QR,24,2015,10,7,2
2,303,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07 00:00:00.000,8.0,8.0,QR,16,2015,10,7,2
3,305,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00.000,16.0,16.0,QR,32,2015,1,7,2
4,307,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07 12:09:09.000,11.0,11.0,QR,22,2015,10,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2757,3700,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08 00:00:00.000,NaN,8.0,QR,8,2022,7,8,4
2758,3701,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12 00:00:00.000,NaN,8.0,QR,8,2022,10,12,2
2759,4951,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29 00:00:00.000,NaN,5.0,QR,5,2022,9,29,3
2760,4952,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18 00:00:00.000,NaN,5.0,QR,5,2023,1,18,2
2761,4953,세양청마루 아파트 앞,강동구,강동구 천호대로 1162,37.533466,127.140503,2023-07-13 00:00:00.000,NaN,10.0,QR,10,2023,7,13,3

In [147]:
file_name = "bike_station.json"
df.to_json(file_name, force_ascii=False, orient='table', lines=False, indent=2, index=False)

In [149]:
df3 = pd.read_json(file_name,orient='table',lines=False)
df3

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,자전거수,연도,월,일,요일
0,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46.000,20.0,20.0,QR,40,2015,10,7,2
1,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07 12:04:22.000,12.0,12.0,QR,24,2015,10,7,2
2,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07 00:00:00.000,8.0,8.0,QR,16,2015,10,7,2
3,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00.000,16.0,16.0,QR,32,2015,1,7,2
4,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07 12:09:09.000,11.0,11.0,QR,22,2015,10,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2757,3700.0,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08 00:00:00.000,NaN,8.0,QR,8,2022,7,8,4
2758,3701.0,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12 00:00:00.000,NaN,8.0,QR,8,2022,10,12,2
2759,4951.0,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29 00:00:00.000,NaN,5.0,QR,5,2022,9,29,3
2760,4952.0,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18 00:00:00.000,NaN,5.0,QR,5,2023,1,18,2
2761,4953.0,세양청마루 아파트 앞,강동구,강동구 천호대로 1162,37.533466,127.140503,2023-07-13 00:00:00.000,NaN,10.0,QR,10,2023,7,13,3